pipeline {
  agent {
    label 'docker'
  }

  stages {
    stage('Build') {
      steps {
        echo 'Building applicaiton...'

      }
    }
    stage('Test') {
      steps {
        echo 'Running Tests!!'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploying Applicaiton!'
      }
    }

  }
}
